### ISSUE TITLE
local build fails to run gateway process

### ISSUE THREAD

**Issue by fireinmyveins** [Voyz/ibeam#143]
**Describe the bug**
if i pull the repo and build the image locally using the command from the "build_multiplatform.sh" :
`docker buildx build --platform linux/amd64,linux/arm64 -t me/custom_image_name --push .`

and then run the resulted image using
`docker compose up -d`
 
while having the "docker-compose.yml"

```
version: "2.1"

services:
  ibeam:
    image: me/custom_image_name
    container_name: ibeam
    env_file:
      - env.list
    ports:
      - 127.0.0.1:5000:5000
      - 127.0.0.1:5001:5001
    network_mode: bridge # Required due to clientportal.gw IP restrictions
    restart: 'no' # Prevents IBEAM_MAX_FAILED_AUTH from being exceeded
```

the logs of the container point that the gateway java process failed to start and in the docker container logs i have the following :

2023-06-05 17:12:38,128|I| ############ Starting IBeam version 0.4.5 ############
2023-06-05 17:12:38,139|I| Secrets source: env
2023-06-05 17:12:38,141|I| Health server started at port=5001
2023-06-05 17:12:38,142|I| Environment variable configuration:
2023-06-05 17:12:38,142|I| Gateway not found, starting new one...
2023-06-05 17:12:38,142|I| Note that the Gateway log below may display "Open https://localhost:5000 to login" - ignore this command.
2023-06-05 17:12:38,143|I| Starting Gateway as Linux process with params: ['bash', 'bin/run.sh', 'root/conf.yaml']
running  
 runtime path : root:dist/ibgroup.web.core.iblink.router.clientportal.gw.jar:build/lib/runtime/*
 config file  : root/conf.yaml
Exception in thread "main" java.lang.NoClassDefFoundError: org/slf4j/LoggerFactory
        at io.vertx.core.logging.SLF4JLogDelegate.<init>(SLF4JLogDelegate.java:36)
        at io.vertx.core.logging.SLF4JLogDelegateFactory.createDelegate(SLF4JLogDelegateFactory.java:29)
        at io.vertx.core.logging.LoggerFactory.getLogger(LoggerFactory.java:79)
        at io.vertx.core.logging.LoggerFactory.getLogger(LoggerFactory.java:72)
        at ibgroup.web.core.clientportal.gw.GatewayStart.<clinit>(GatewayStart.java:24)
Caused by: java.lang.ClassNotFoundException: org.slf4j.LoggerFactory
        at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:581)
        at java.base/jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(ClassLoaders.java:178)
        at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:522)
        ... 5 more
2023-06-05 17:12:39,147|E| Cannot communicate with the Gateway. Consider increasing IBEAM_GATEWAY_STARTUP
2023-06-05 17:12:39,155|I| Starting maintenance with interval 60 seconds

what am i doing wrong ?
