### ISSUE TITLE
Access denied with conf.yaml having allowed IPs

### ISSUE THREAD

**Issue by this-josh** [Voyz/ibeam#207]
First, thanks for this package alongside Ibind. I'm trying to setup a docker compose which runs Ibeam as a service alongside Ibind.

**Describe the bug**
I have the following docker compose
```yaml
services:
  ibeam:
    image: voyz/ibeam
    container_name: ibeam
    ports:
      - "5001:5000"
    networks:
      - my-network
    restart: 'no'
    environment:
      - IBEAM_ACCOUNT=${IBEAM_ACCOUNT}
      - IBEAM_PASSWORD=${IBEAM_PASSWORD}
      - IBEAM_INPUTS_DIR=/srv/inputs
    volumes:
      - type: "bind"
        source: "inputs"
        target: "/srv/inputs"
        read_only: true
            
  deployment:
    build: .
    container_name: deployment
    networks:
      - my-network
    depends_on:
      - ibeam

networks:
  my-network:
    driver: bridge
```

When I run this my laptop can access ibeam as expected on port 5001 (5000 is in use on macs), but the deployment service cannot, it gets `Access Denied` issues.

I've read through all the relevant documentation I can find, I've got my conf.yaml setup `ibeam       | 2024-07-17 14:32:43,055|I| Custom conf.yaml found and will be used by the Gateway` and in this I have setup an allow list
```yaml
ips:
  allow:
    - 192.*
    - 131.216.*
    - 127.0.0.1
    - 0.0.0.0
    - 172.17.0.*
    - 45.41.174.156
    - 172.17.0.*
    - MY.IP.ADDRESS
  deny:
    - 212.90.324.10
  ```

**Environment**
IBeam version:0.5.1(latest) and 0.5.4
Docker image or standalone: Docker image
Python version (standalone users only):
OS: MacOS

**Suggest a Fix**
I'm really not sure given from my laptop 
```python
import requests
url = "https://localhost:5001/demo#"
response = requests.get(url,verify=False)
print(response.text)
```
Looks correct but I get this from the deployment services' shell
```python
>>> import requests
>>> 
>>> url = "https://ibeam:5000/demo#"
>>> response = requests.get(url,verify=False)
/usr/local/lib/python3.12/site-packages/urllib3/connectionpool.py:1099: InsecureRequestWarning: Unverified HTTPS request is being made to host 'ibeam'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#tls-warnings
  warnings.warn(
>>> print(response.text)
Access Denied
```
Getting the Access Denied error demonstrates that the request is getting through to ibeam as if the networks aren't configured correctly I get connection issues errors, for example when I have  tried having the network setup as `network_mode: "bridge"` I find both
```python
url = "https://localhost:5000/demo#"
url = "https://ibeam:5000/demo#"
```
give this error suggesting the network isn't setup correctly
```
requests.exceptions.ConnectionError: HTTPSConnectionPool(host='ibeam', port=5000): Max retries exceeded with url: /demo (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0xffff814a1e50>: Failed to resolve 'ibeam' ([Errno -2] Name or service not known)"))
```
