### ISSUE TITLE
Port 5000 occupied in OSX

### ISSUE THREAD

**Issue by Guster47** [Voyz/ibeam#232]
I am running my client portal gateway on my dev machine that is running OSX. 
Unfortunately in OSX the port 5000 is occupied for airdrop functionalities and therefor I have setup my client portal gateway to run on port 5055. I want to implement the use of IBeam to automate the login to my broker account but it uses the default port 5000 and I can't figure out what I would have to do for editing the port. Thanks.

**Comment by Voyz** [comment]
Hey @Guster47 thanks for reporting your issue. Please see https://github.com/Voyz/ibeam/wiki/Gateway-Configuration for how to change the IP. Let me know if that works for you 👍

**Comment by Guster47** [comment]
Thanks @Voyz ! I’ll give it a try—it looks like it should solve the issue with the gateway.
I'll let you know if it works!

Thanks again!

**Comment by Guster47** [comment]
Hello @Voyz,

I tried adding the volume mount with my custom `conf.yaml` in the `compose.yaml` file that I use to run `docker-compose up`, but it doesn’t seem to be applied correctly. In Docker Desktop, I don’t see the mounted volume (I’m still fairly new to Docker, so apologies if I’m missing something).

I suspect this because the container's console still instructs me to log in to the Client Portal Gateway at `https://localhost:5000` instead of `5055`, which suggests that my custom configuration isn't being recognized.

Here’s my `compose.yaml`:

```
services:
  ibeam:
    image: voyz/ibeam
    container_name: ibeam
    env_file:
      - env.list
    ports:
      - 5055:5055
      - 5001:5001
    network_mode: bridge # Required due to clientportal.gw IP whitelist
    restart: 'no' # Prevents IBEAM_MAX_FAILED_AUTH from being exceeded
    volumes:
      - /Users/me/loca/path/to/ibeam/inputs:/srv/inputs
```
