### ISSUE TITLE
Need to add 172.17.0.* to conf.yaml

### ISSUE THREAD

**Issue by DoingIsKing** [Voyz/ibeam#47]
I need to add 172.17.0.* to the conf.yaml to allow access to https://localhost:5000 from Chrome
The problem is, I'm a Windows guy and I'm lost in the terminology. 
I need clear instructions on how find and edit my conf.yaml file.

Thanks

**Environment**
IBeam version: Last one as of Dec 24, 2021
Docker image 
Docker version 19.03.01
OS: Windows 7

**Comment by murtazayusuf** [comment]
You should check the wiki section.

**Comment by DoingIsKing** [comment]
That's what brought me here.

**Comment by maksimstojkovic** [comment]
@DoingIsKing the file you are referring to can be found here:
[https://github.com/Voyz/ibeam/blob/master/copy_cache/clientportal.gw/root/conf.yaml](https://github.com/Voyz/ibeam/blob/master/copy_cache/clientportal.gw/root/conf.yaml)

To my understanding, it already allows connections over the range 172.17.0.* (same as 172.17.0.0/24) via the <u>default docker bridge network</u>.

```
ips:
  allow:
    - 192.*
    - 131.216.*
    - 127.0.0.1
    - 0.0.0.0
    - 172.17.0.*
  deny:
    - 212.90.324.10
```

A caveat is that this current configuration may not work as expected if used in a different docker network (e.g. a network created by docker-compose) without the appropriate settings.

The following line should be used in [docker-compose files](https://github.com/Voyz/ibeam/blob/9ab9f879c7e83f85933a1db129614933a88c9f8a/docker-compose.yml) to prevent this issue:

```
services:
  ibeam:
    image: voyz/ibeam
    ...
    network_mode: bridge # Required due to clientportal.gw IP restrictions
```
