### ISSUE TITLE
Unable to find propery p2loc on class

### ISSUE THREAD

**Issue by MislavSag** [Voyz/ibeam#83]
**Describe the bug**
I have tried to run gateway in Linode server using following video:
https://www.youtube.com/watch?v=J2F6PrPUG6w&t=57s

In the end, after I have set IBEAM_ACCOUNT and IBEAM_PASSWORD, and added IP to allowed port in conf.yaml file:
```
ip2loc: "US"
proxyRemoteSsl: true
proxyRemoteHost: "https://api.ibkr.com"
listenPort: 5000
listenSsl: true
svcEnvironment: "v1"
sslCert: "vertx.jks"
sslPwd: "mywebapi"
authDelay: 3000
portalBaseURL: ""
serverOptions:
    blockedThreadCheckInterval: 1000000
    eventLoopPoolSize: 20
    workerPoolSize: 20
    maxWorkerExecuteTime: 100
    internalBlockingPoolSize: 20
cors:
    origin.allowed: "*"
    allowCredentials: false
webApps:
    - name: "demo"
      index: "index.html"
ips:
  allow:
    - 192.*
    - 131.216.*
    - 127.0.0.1
    - 0.0.0.0
    - 172.17.0.*
    - 93.*
  deny:
    - 212.90.324.10
```
I got an error:
```

Cannot create property=p2loc for JavaBean=ibgroup.web.core.clientportal.gw.Config@7e0b85f9
in 'reader ', line 1, column 1:
     p2loc: "US"
     ^
Unable to find propery p2loc on class: ibgroup.web.core.clientportal.gw.Config in reader, line 1 column 8:
p2loc: "US"
            ^

```

**To Reproduce**
See the description

**Expected behavior**
Gateway starts as expected.

**Environment**
IBeam version: 
Docker image or standalone: docker image 
Python version (standalone users only): 
OS: Debian

**Comment by Voyz** [comment]
Hey @MislavSag thanks for reporting your bug 👍 Can you check what line endings your `conf.yaml` file has? It should be LF.

Also, note that this tutorial you linked is partially inaccurate and we don't recommend following it.

**Comment by MislavSag** [comment]
I tried to add a new line and run again with the command:
```
docker run -v /root/inputs:/srv/inputs --env-file env.list -p 5000:5000 voyz/ibeam
```
I get the sam error.
I want to add I am nt from US, but from Europe (Croatia).
Can you please explain which part is innacurate?

**Comment by MislavSag** [comment]
I was following instructions in the video an created server with Debian.

Debian GNU/Linux 10 (buster)
Version_ID = 10

**Comment by Voyz** [comment]
Thanks. And how about your development system? The computer you use to develop?

**Comment by MislavSag** [comment]
It is shared CPU on Linode: Nanode 1GB.

**Comment by Voyz** [comment]
Okay thanks. Can you send me your modified `conf.yaml` file?

**Comment by MislavSag** [comment]
```
ip2loc: "US"
proxyRemoteSsl: true
proxyRemoteHost: "https://api.ibkr.com"
listenPort: 5000
listenSsl: true
svcEnvironment: "v1"
sslCert: "vertx.jks"
sslPwd: "mywebapi"
authDelay: 3000
portalBaseURL: ""
serverOptions:
    blockedThreadCheckInterval: 1000000
    eventLoopPoolSize: 20
    workerPoolSize: 20
    maxWorkerExecuteTime: 100
    internalBlockingPoolSize: 20
cors:
    origin.allowed: "*"
    allowCredentials: false
webApps:
    - name: "demo"
      index: "index.html"
ips:
  allow:
    - 192.*
    - 131.216.*
    - 127.0.0.1
    - 0.0.0.0
    - 172.17.0.*
    - 93.*
  deny:
    - 212.90.324.10


```
